version: '1.0'
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
  postgre:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - postgre-db:/val/lib/postgresql/data1
volumes:
  postgre-db: