// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/tinyurl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=FullURL,proto3" json:"FullURL,omitempty"`
}

func (x *URL) Reset() {
	*x = URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tinyurl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

type HashedURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`
}

func (x *HashedURL) Reset() {
	*x = HashedURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tinyurl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashedURL) ProtoMessage() {}

func (x *HashedURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashedURL.ProtoReflect.Descriptor instead.
func (*HashedURL) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{1}
}

func (x *HashedURL) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

var File_proto_tinyurl_proto protoreflect.FileDescriptor

var file_proto_tinyurl_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x22, 0x1f,
	0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x22,
	0x27, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x32, 0x66, 0x0a, 0x0a, 0x55, 0x72, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x54, 0x69, 0x6e, 0x79, 0x55, 0x52,
	0x4c, 0x12, 0x0c, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x2e, 0x55, 0x52, 0x4c, 0x1a,
	0x12, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64,
	0x55, 0x52, 0x4c, 0x12, 0x2b, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x12, 0x12,
	0x2e, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x55,
	0x52, 0x4c, 0x1a, 0x0c, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x75, 0x72, 0x6c, 0x2e, 0x55, 0x52, 0x4c,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_tinyurl_proto_rawDescOnce sync.Once
	file_proto_tinyurl_proto_rawDescData = file_proto_tinyurl_proto_rawDesc
)

func file_proto_tinyurl_proto_rawDescGZIP() []byte {
	file_proto_tinyurl_proto_rawDescOnce.Do(func() {
		file_proto_tinyurl_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tinyurl_proto_rawDescData)
	})
	return file_proto_tinyurl_proto_rawDescData
}

var file_proto_tinyurl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tinyurl_proto_goTypes = []interface{}{
	(*URL)(nil),       // 0: tinyurl.URL
	(*HashedURL)(nil), // 1: tinyurl.HashedURL
}
var file_proto_tinyurl_proto_depIdxs = []int32{
	0, // 0: tinyurl.UrlService.TinyURL:input_type -> tinyurl.URL
	1, // 1: tinyurl.UrlService.FullURL:input_type -> tinyurl.HashedURL
	1, // 2: tinyurl.UrlService.TinyURL:output_type -> tinyurl.HashedURL
	0, // 3: tinyurl.UrlService.FullURL:output_type -> tinyurl.URL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tinyurl_proto_init() }
func file_proto_tinyurl_proto_init() {
	if File_proto_tinyurl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tinyurl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tinyurl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashedURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tinyurl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tinyurl_proto_goTypes,
		DependencyIndexes: file_proto_tinyurl_proto_depIdxs,
		MessageInfos:      file_proto_tinyurl_proto_msgTypes,
	}.Build()
	File_proto_tinyurl_proto = out.File
	file_proto_tinyurl_proto_rawDesc = nil
	file_proto_tinyurl_proto_goTypes = nil
	file_proto_tinyurl_proto_depIdxs = nil
}
